<?xml version="1.0" encoding="UTF-8"?>
<project xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xmlns="http://maven.apache.org/POM/4.0.0"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
  <modelVersion>4.0.0</modelVersion>
  <parent>
    <groupId>io.github.michaelstahelena</groupId>
    <artifactId>poc-contract-testing</artifactId>
    <version>1.0.0-SNAPSHOT</version>
  </parent>
  <artifactId>provider-user-java</artifactId>
  <dependencies>
    <dependency>
      <groupId>org.springframework.boot</groupId>
      <artifactId>spring-boot-starter-web</artifactId>
    </dependency>
    <dependency>
      <groupId>org.springframework.boot</groupId>
      <artifactId>spring-boot-starter-test</artifactId>
      <scope>test</scope>
    </dependency>
    <dependency>
      <groupId>au.com.dius.pact.provider</groupId>
      <artifactId>spring6</artifactId>
      <version>${pact-jvm.version}</version>
      <scope>test</scope>
    </dependency>
    <dependency>
      <groupId>au.com.dius.pact.provider</groupId>
      <artifactId>junit5</artifactId>
      <version>${pact-jvm.version}</version>
      <scope>test</scope>
    </dependency>
  </dependencies>
  <build>
    <plugins>
      <plugin>
        <groupId>org.springframework.boot</groupId>
        <artifactId>spring-boot-maven-plugin</artifactId>
      </plugin>
      <plugin>
        <groupId>org.apache.maven.plugins</groupId>
        <artifactId>maven-surefire-plugin</artifactId>
        <version>3.5.2</version>
        <configuration>
          <useSystemClassLoader>false</useSystemClassLoader>
          <systemPropertyVariables>
            <pactbroker.url>${pactbroker.url}</pactbroker.url>
            <pactbroker.auth.username>${pactbroker.auth.username}</pactbroker.auth.username>
            <pactbroker.auth.password>${pactbroker.auth.password}</pactbroker.auth.password>
            <pact.provider.version>${pact.provider.version}</pact.provider.version>
            <pact.verifier.publishResults>${pact.verifier.publishResults}</pact.verifier.publishResults>
          </systemPropertyVariables>
        </configuration>
      </plugin>
    </plugins>
  </build>
</project>
